export const Models = {
    Admin: 'Admin',
    Adresse: 'Adresse',
    Chat: 'Chat',
    Commande: 'Commande',
    Confectionne: 'Confectionne',
    Contient: 'Contient',
    Ingredient: 'Ingredient',
    Menu: 'Menu',
    Panier: 'Panier',
    PanierMenu: 'PanierMenu',
    PanierProduit: 'PanierProduit',
    Present: 'Present',
    Produit: 'Produit',
    PromoMenu: 'PromoMenu',
    PromoPanier: 'PromoPanier',
    PromoProduit: 'PromoProduit',
    Promotion: 'Promotion',
    Restaurant: 'Restaurant',
    Session: 'Session',
    User: 'User',
    Vend: 'Vend'
};