version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27035:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: esgi-zoo
      MONGO_INITDB_ROOT_PASSWORD: poiuytreza1234!@

  api:
    build: .
    restart: always
    ports:
      - 8080:3000
    env_file:
      - ".env"
